### ISSUE TITLE
Why not source 

### ISSUE THREAD

**Issue by evanzh7** [taizilongxu/interview_python#1]
直接就在readme里写 这样好吗

**Comment by taizilongxu** [comment]
那写到哪里啊？

**Comment by evanzh7** [comment]
不分个篇章吗，可以卸载issue里啊。
like [this](https://github.com/lifesinger/lifesinger.github.com/issues?q=label%3Ablog)

**Comment by taizilongxu** [comment]
写在一个里方便看看,想到啥写啥
