### ISSUE TITLE
关于协程

### ISSUE THREAD

**Issue by lytofb** [taizilongxu/interview_python#23]
个人理解协程是对线程/进程同步的编程语法的一个统称，比如python中使用yield，coroutine等关键字进行线程/进程间同步，就避免了显式地使用wait，notify等关键字来进行同步。虽然线程，进程，协程都带程字，但是协程和前两者应该不属于一类

**Comment by taizilongxu** [comment]
还是不太一样的, 协程就不需要考虑同步异步的问题了, 因为切换的问题是交给用户自己控制了

**Comment by lytofb** [comment]
恩，这个地方是我理解错了
参见https://segmentfault.com/a/1190000000663472
和http://www.cnblogs.com/lhfcws/p/4148227.html

**Comment by lytofb** [comment]
线程确实比协程性能更好。因为线程能利用多核达到真正的并行计算，如果任务设计的好，线程能几乎成倍的提高你的计算能力，说线程性能不好的很多是因为没有设计好导致大量的锁、切换、等待，这些很多都是应用层的问题。而协程因为是非抢占式，所以需要用户自己释放使用权来切换到其他协程，因此同一时间其实只有一个协程拥有运行权，相当于单线程的能力。我们在x360、xbox1和ps4上做游戏的时候，开线程用来做数据加载、解压这种不需要或者很少需要数据同步的任务的时候效率杠杠的，而协程用来处理一些应用层逻辑调度的时候非常方便。官方文档也建议，协程只是为了老代码移植和兼容性，不推荐新代码使用。

**Comment by taizilongxu** [comment]
恩, 你说的对,
但是python 里算比较特殊, 因为只能用单核. 
你说的官方文档是?
