### ISSUE TITLE
27 题中 readlines 返回的是列表而不是迭代器

### ISSUE THREAD

**Issue by tonghuashuai** [taizilongxu/interview_python#25]
官方解释：
`Read until EOF using readline() and return a **_list_** containing the lines thus read.`
使用 xreadlines 返回的才是迭代器。

另外，希望能说明一点，xreadlines 已经在 2.3 版本以后废弃，改用 for line in file 替代。

**Comment by lambdaplus** [comment]
确实是列表

**Comment by taizilongxu** [comment]
fix

**Comment by lambdaplus** [comment]
没有 fix 啊 截止到 2017 03 21 依然是 迭代器
