### ISSUE TITLE
单链表存在节点交叉的情况？

### ISSUE THREAD

**Issue by x1ah** [taizilongxu/interview_python#34]
我也遇见过这个面试题，让寻找两个单链表的交叉节点，但是两个单链表是不可能存在有交叉节点的情况的。一个节点只有一个前驱和一个后继，如何相交？所以这里的链表交叉算法是否有问题？thx！

**Comment by EINDEX** [comment]
存在交叉节点的两个单链表 只可能是 Y 字形或者 V 字形。

**Comment by x1ah** [comment]
@EINDEX 如果是 Y 型或 V 型也就代表同一个节点有两个前驱了。（单链表）XD

**Comment by EINDEX** [comment]
@x1ah 这个单链表不需要用到前驱  应该是[单向链表](https://zh.wikipedia.org/wiki/单向链表)

**Comment by x1ah** [comment]
@EINDEX  啊哈，糊涂了，get，thx！
