### ISSUE TITLE
字符串格式化和format

### ISSUE THREAD

**Issue by Damnever** [taizilongxu/interview_python#5]
[字符串格式化和format](https://github.com/taizilongxu/interview_python#8-字符串格式化和format)

> format在许多方面看起来更便利.你可以重用参数,但是你用%就不行

你确定???

```
>>> data = {'name': 'Bob', 'age': 20}
>>> '%(name)s is %(age)d years old, and %(name)s is a boy.' % data
'Bob is 20 years old, and Bob is a boy.'
```

**Comment by taizilongxu** [comment]
http://stackoverflow.com/questions/5082452/python-string-formatting-vs-format
确实啊, 我理解有误, thank you : )
